In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from geopy.geocoders import Nominatim
import time

In [3]:
file_path1 = "./my_addresses_geocoded.csv"

not_found = pd.read_csv(file_path1)

In [4]:
# #Get the coordinates of the non matched trip advisor restaurants

# # create a Nominatim geocoder object
# geolocator = Nominatim(user_agent='myapplication')


# # create new columns for latitude and longitude
# # not_found['latitude'] = ''
# # not_found['longitude'] = ''

# # loop over each row in the DataFrame and geocode the address
# #for i, row in not_found.iterrows():
# for i, row in not_found.iloc[1450:].iterrows():
#     address = row['address_trip']
#     location = geolocator.geocode(address) # get the location object for the address
#     if location:
#         not_found.at[i, 'latitude'] = location.latitude # update the latitude for this row
#         not_found.at[i, 'longitude'] = location.longitude # update the longitude for this row
#         print(f"Geocoded address {i+1}: {address} -> ({location.latitude}, {location.longitude})")
#     else:
#         print(f"Failed to geocode address {i+1}: {address}")
#     time.sleep(1) # wait for 1 second before making the next request

#     # save the updated DataFrame to a new CSV file every 10 records
#     if (i+1) % 10 == 0:
#         filename = f"my_addresses_geocoded.csv"
#         not_found.to_csv(filename, index=False)
#         print(f"Saved geocoded addresses to {filename}")

# # save the final version of the DataFrame to a new CSV file
# not_found.to_csv('my_addresses_geocoded.csv', index=False)

In [20]:
#get the google df and try to match with the google df ith the latitude and longitude
google_df = pd.read_csv('../definitive_files_integration/google_places_cleaned_DEFINITIVE.csv')
trip_df = pd.read_csv('./my_addresses_geocoded.csv')
import ast
for index, row in google_df.iterrows():
    # Parse the 'geometry' field as a dictionary
    geometry_dict = ast.literal_eval(row['geometry'])
    
    # Extract the 'lat' and 'lng' values
    lat_value = geometry_dict['lat']
    lng_value = geometry_dict['lng']
    
    # Round the values to the third decimal place
    lat_rounded = round(lat_value, 10)
    lng_rounded = round(lng_value, 10)
    
    # Assign the rounded values to new columns 'latitude' and 'longitude'
    google_df.at[index, 'latitude'] = lat_rounded
    google_df.at[index, 'longitude'] = lng_rounded

# # drop the original geometry column and temporary dataframe
# google_df = google_df.drop(columns='geometry')
# # drop the original geometry column
# google_df = google_df.drop(columns='geometry')
trip_df

,id_trip,name_trip,rating_trip,total_reviews_trip,cook_type_trip,price_level_trip,address_trip,reviews,formatted_name_trip,formatted_address_trip,latitude,longitude
0,10,Kebabbar Star Zagros,5.0,416,"Mediorientale, Turca",1,"Corso 22 Marzo,38, 20135 Milano Italia","[{'bubbles': 'bubble_50', 'title': 'Una piacev...",starzagros,corso22marzo38,45.462221,9.223890
1,21,Piadineria Artigianale Pascoli,4.0,928,"Italiana, Fast food",1,"Via Niccolò Paganini, 2, 20131 Milano Italia","[{'bubbles': 'bubble_50', 'title': 'Piadine fr...",piadineriaartigianalepascoli,vianiccolòpaganini2,45.483396,9.215458
2,25,Al Bacio Navigli,4.0,163,"Italiana, Contemporanea",2.5,"Via Vigevano 32, 20144 Milano Italia","[{'bubbles': 'bubble_40', 'title': 'sosta velo...",albacionavigli,viavigevano32,45.453254,9.171103
3,34,Pizza Shambo,4.0,178,"Pizza, Italiana",2.5,"Via Edolo 1, 20125 Milano Italia","[{'bubbles': 'bubble_30', 'title': 'Pizza a me...",pizzashambo,viaedolo1,45.494405,9.207202
4,37,Wave Cocktail Bar,5.0,351,"Europea, Pub",2.5,"Via Edmondo de Amicis 28, 20123 Milano Italia","[{'bubbles': 'bubble_10', 'title': 'Accoglienz...",wavecocktail,viaedmondodeamicis28,45.459069,9.177733
...,...,...,...,...,...,...,...,...,...,...,...,...
3366,6964,La Buttiga Franco's Room,NaN,0,"Italiana, Americana",?,"Via Castelbarco, 17, 20136 Milano Italia",[],labuttigafrancosroom,viacastelbarco17,NaN,NaN
3367,6965,Nk Bar,NaN,0,Pizza,?,"Via Giuseppe Saragat 6, 20128 Milano Italia",[],nkbar,viagiuseppesaragat6,NaN,NaN
3368,6966,Caffè Vergnano 1882,NaN,0,?,?,"Piazza Venticinque Aprile, 10 Eataly Smeraldo,...",[],caffèvergnano1882,piazzaventicinqueaprile10eatalysmeraldo,NaN,NaN
3369,6968,La Puccia Ignorante Xxl,NaN,0,"Italiana, Fast food",1,"Via Filippo Brunelleschi 4, 20146 Milano Italia",[],lapucciaignorantexxl,viafilippobrunelleschi4,NaN,NaN
3370,6969,Wine time milano,NaN,0,?,?,NaN,NaN,winetime,italy,NaN,NaN

In [23]:
# Define your query
query = {"rating_trip": 5.0}

# Execute the query and get the cursor
cursor = collection.find(query)

# Round latitude and longitude columns in both dataframes
trip_df['rounded_latitude'] = np.round(trip_df['latitude'].astype(float), decimals=4)
trip_df['rounded_longitude'] = np.round(trip_df['longitude'].astype(float), decimals=4)
google_df['rounded_latitude'] = np.round(google_df['latitude'].astype(float), decimals=4)
google_df['rounded_longitude'] = np.round(google_df['longitude'].astype(float), decimals=4)


# print(trip_df[trip_df['id_trip'] == 1360])
# print(google_df[google_df['Index'] == 25588])

# Merge dataframes based on rounded latitude and longitude columns
merged_df = trip_df.merge(google_df, how='left', left_on=['rounded_latitude', 'rounded_longitude'], right_on=['rounded_latitude', 'rounded_longitude'])
merged_df.to_csv("./test.csv")
# Find matched and not found records
matched = merged_df[['Index', 'id_trip']].dropna().rename(columns={'Index': 'google', 'id_trip': 'trip'})
not_found = merged_df[['Index', 'id_trip']].isna().rename(columns={'Index': 'google', 'id_trip': 'trip'})

# Print the results
print("found:")
print(matched)
print("not found:")
print(not_found)

attach_not_found = trip_df.merge(matched, how='left', left_on=['id_trip', 'trip'])
attach_not_found.to_csv("./test.csv")

found:
       google  trip
6     14600.0    43
41    22987.0   258
45    10460.0   272
72     8539.0   396
73     8540.0   396
...       ...   ...
3349  11109.0  6883
3355  23572.0  6890
3356  23585.0  6890
3381  31738.0  6930
3389  26310.0  6941

[240 rows x 2 columns]
not found:
      google   trip
0       True  False
1       True  False
2       True  False
3       True  False
4       True  False
...      ...    ...
3405    True  False
3406    True  False
3407    True  False
3408    True  False
3409    True  False

[3410 rows x 2 columns]

MergeError: Must pass "right_on" OR "right_index".