In [2]:
import pandas as pd
import ast

df = pd.read_csv('../output/google_places_no_duplicates.csv')

# Data Cleaning
here the columns: 
business_status	
geometry	
icon	
icon_background_color	
icon_mask_base_uri	
name	
opening_hours	
photos	
place_id	
plus_code	
price_level	
rating	
reference	
scope	
types	
user_ratings_total	
vicinity	
permanently_closed

Step 1. merge permanentrly_closed column (boolean) into business_status (string)

In [27]:
df.loc[df['permanently_closed'] == True, 'business_status'] = 'PERMANENTLY_CLOSED' 
df = df.drop(columns=['permanently_closed'])

KeyError: 'permanently_closed'

In [31]:
df = df[df['business_status'] != 'PERMANENTLY_CLOSED']
count = (df['address_g'].str.contains(', Milano|italy')).sum()
count

TypeError: unsupported operand type(s) for |: 'str' and 'str'

Step 2. Adjust Geometry field according to what we need

In [4]:
df['geometry'] = df['geometry'].apply(lambda x: ast.literal_eval(x)['location'])
df['geometry']

0                   {'lat': 45.4026414, 'lng': 9.1317121}
1       {'lat': 45.40301179999999, 'lng': 9.1337359000...
2                   {'lat': 45.4025059, 'lng': 9.1402384}
3           {'lat': 45.4036108, 'lng': 9.151838500000002}
4            {'lat': 45.40361069999999, 'lng': 9.1520207}
                              ...
8496                {'lat': 45.5335226, 'lng': 9.2309928}
8497                {'lat': 45.5335226, 'lng': 9.2309928}
8498                   {'lat': 45.53344, 'lng': 9.238436}
8499        {'lat': 45.5335868, 'lng': 9.238451399999999}
8500                {'lat': 45.5327778, 'lng': 9.2472222}
Name: geometry, Length: 8501, dtype: object

In [5]:
df = df.drop(columns=['icon','icon_background_color','icon_background_color','icon_mask_base_uri', 'opening_hours', 'photos', 'plus_code', 'reference', 'scope'])
df

,Index,business_status,geometry,name,place_id,types,vicinity,rating,user_ratings_total,price_level
0,0,OPERATIONAL,"{'lat': 45.4026414, 'lng': 9.1317121}",Rasoi baget,ChIJO3sglmrDhkcRRGm8QM7A9l8,"['meal_takeaway', 'restaurant', 'food', 'point...","Via Roma, Assago",NaN,NaN,NaN
1,3,PERMANENTLY_CLOSED,"{'lat': 45.40301179999999, 'lng': 9.1337359000...",Italiano,ChIJoxvp1MzDhkcRICqmEED4LLU,"['restaurant', 'point_of_interest', 'food', 'e...","Via Giovanni XXIII, 6, Assago",NaN,NaN,NaN
2,6,OPERATIONAL,"{'lat': 45.4025059, 'lng': 9.1402384}",The Blue Crab,ChIJUV3fhHzDhkcRK6xsPTkbcn0,"['restaurant', 'food', 'point_of_interest', 'e...","Via Giuseppe di Vittorio, 4, Assago",4.3,4.0,NaN
3,8,OPERATIONAL,"{'lat': 45.4036108, 'lng': 9.151838500000002}",Burger King,ChIJG_daUl3DhkcRd-n6BP2V4lg,"['restaurant', 'food', 'point_of_interest', 'e...","Viale Milanofiori, Assago",3.4,593.0,1.0
4,9,OPERATIONAL,"{'lat': 45.40361069999999, 'lng': 9.1520207}",Focacceria Saporita,ChIJ1VYAFmjDhkcROsnNIU-PJ9Q,"['restaurant', 'food', 'point_of_interest', 'e...","Viale Milano Fiori, 1, Assago",3.6,36.0,NaN
...,...,...,...,...,...,...,...,...,...,...
8496,37252,OPERATIONAL,"{'lat': 45.5335226, 'lng': 9.2309928}",Ristorante La cittadella,ChIJG2i1O6q5hkcRnXCk1UjGWuo,"['restaurant', 'food', 'point_of_interest', 'e...","Via Roma, Milano",NaN,NaN,NaN
8497,37253,PERMANENTLY_CLOSED,"{'lat': 45.5335226, 'lng': 9.2309928}",LA DANIMARCA,ChIJXbXxO4q5hkcR55G9H8DO-ds,"['restaurant', 'food', 'point_of_interest', 'e...","Via Roma, Milano",5.0,1.0,NaN
8498,37263,OPERATIONAL,"{'lat': 45.53344, 'lng': 9.238436}",Pizzeria Gerry,ChIJ3xof9Jy4hkcRgxDt1uNNteY,"['restaurant', 'food', 'point_of_interest', 'e...","Via Felice Cavallotti, 321, Sesto San Giovanni",3.9,90.0,1.0
8499,37265,OPERATIONAL,"{'lat': 45.5335868, 'lng': 9.238451399999999}",chips & Snacks Amsterdam,ChIJGQbR9Jy4hkcR0PLUQ2mA5bM,"['bar', 'restaurant', 'food', 'point_of_intere...","Via Camillo Benso Cavour, 28, Sesto San Giovanni",4.1,34.0,NaN
8500,37268,OPERATIONAL,"{'lat': 45.5327778, 'lng': 9.2472222}",Happy Moments Restaurant,ChIJ40a0YIG4hkcRk43xKuUhkyU,"['restaurant', 'food', 'point_of_interest', 'e...","Viale Thomas Alva Edison, 452, Sesto San Giovanni",4.5,828.0,2.0

In [6]:
df.isna().sum()

Index                    0
business_status          0
geometry                 0
name                     0
place_id                 0
types                    0
vicinity                 0
rating                1183
user_ratings_total    1183
price_level           4882
dtype: int64

In [21]:
# Check if there are some restaurants with the same name
df_grouped = df.groupby('name').size().reset_index(name='counts')
result = df_grouped[df_grouped['counts'] > 1]
result.to_csv('../output/duplicates_name.csv')

In [22]:
new_col_names = {'price_level': 'price_level_g',
                'rating': 'rating_g',
                'user_ratings_total': 'total_reviews_g',
                'price_level': 'price_level_g',
                'vicinity': 'address_g',
                'name': 'name_g'}
df = df.rename(columns=new_col_names)
df

,Index,business_status,geometry,name_g,place_id,types,address_g,rating_g,total_reviews_g,price_level_g
0,0,OPERATIONAL,"{'lat': 45.4026414, 'lng': 9.1317121}",Rasoi baget,ChIJO3sglmrDhkcRRGm8QM7A9l8,"['meal_takeaway', 'restaurant', 'food', 'point...","Via Roma, Assago",NaN,NaN,NaN
1,3,PERMANENTLY_CLOSED,"{'lat': 45.40301179999999, 'lng': 9.1337359000...",Italiano,ChIJoxvp1MzDhkcRICqmEED4LLU,"['restaurant', 'point_of_interest', 'food', 'e...","Via Giovanni XXIII, 6, Assago",NaN,NaN,NaN
2,6,OPERATIONAL,"{'lat': 45.4025059, 'lng': 9.1402384}",The Blue Crab,ChIJUV3fhHzDhkcRK6xsPTkbcn0,"['restaurant', 'food', 'point_of_interest', 'e...","Via Giuseppe di Vittorio, 4, Assago",4.3,4.0,NaN
3,8,OPERATIONAL,"{'lat': 45.4036108, 'lng': 9.151838500000002}",Burger King,ChIJG_daUl3DhkcRd-n6BP2V4lg,"['restaurant', 'food', 'point_of_interest', 'e...","Viale Milanofiori, Assago",3.4,593.0,1.0
4,9,OPERATIONAL,"{'lat': 45.40361069999999, 'lng': 9.1520207}",Focacceria Saporita,ChIJ1VYAFmjDhkcROsnNIU-PJ9Q,"['restaurant', 'food', 'point_of_interest', 'e...","Viale Milano Fiori, 1, Assago",3.6,36.0,NaN
...,...,...,...,...,...,...,...,...,...,...
8496,37252,OPERATIONAL,"{'lat': 45.5335226, 'lng': 9.2309928}",Ristorante La cittadella,ChIJG2i1O6q5hkcRnXCk1UjGWuo,"['restaurant', 'food', 'point_of_interest', 'e...","Via Roma, Milano",NaN,NaN,NaN
8497,37253,PERMANENTLY_CLOSED,"{'lat': 45.5335226, 'lng': 9.2309928}",LA DANIMARCA,ChIJXbXxO4q5hkcR55G9H8DO-ds,"['restaurant', 'food', 'point_of_interest', 'e...","Via Roma, Milano",5.0,1.0,NaN
8498,37263,OPERATIONAL,"{'lat': 45.53344, 'lng': 9.238436}",Pizzeria Gerry,ChIJ3xof9Jy4hkcRgxDt1uNNteY,"['restaurant', 'food', 'point_of_interest', 'e...","Via Felice Cavallotti, 321, Sesto San Giovanni",3.9,90.0,1.0
8499,37265,OPERATIONAL,"{'lat': 45.5335868, 'lng': 9.238451399999999}",chips & Snacks Amsterdam,ChIJGQbR9Jy4hkcR0PLUQ2mA5bM,"['bar', 'restaurant', 'food', 'point_of_intere...","Via Camillo Benso Cavour, 28, Sesto San Giovanni",4.1,34.0,NaN
8500,37268,OPERATIONAL,"{'lat': 45.5327778, 'lng': 9.2472222}",Happy Moments Restaurant,ChIJ40a0YIG4hkcRk43xKuUhkyU,"['restaurant', 'food', 'point_of_interest', 'e...","Viale Thomas Alva Edison, 452, Sesto San Giovanni",4.5,828.0,2.0

In [24]:
df.groupby("name_g").count() > 1

,Index,business_status,geometry,place_id,types,address_g,rating_g,total_reviews_g,price_level_g
name_g,,,,,,,,,
"""DAVET "" TURKISH -KEBAP PIZZERIA-GRILL",False,False,False,False,False,False,False,False,False
"""El Mojito""",False,False,False,False,False,False,False,False,False
"""LE CASE"" RISTORANTE ASIAN FUSION",False,False,False,False,False,False,False,False,False
"""Woodstock dal 1969”",False,False,False,False,False,False,False,False,False
#555food and sport,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
맛집...비아.바구타,False,False,False,False,False,False,False,False,False
미가 MIGA Ristorante Coreano,False,False,False,False,False,False,False,False,False
밀라노 아이스크림,False,False,False,False,False,False,False,False,False
샤브샤브 중국집,False,False,False,False,False,False,False,False,False
프라텔리 식당,False,False,False,False,False,False,False,False,False

In [25]:
df.to_csv('../output/google_places_cleaned.csv')